### ISSUE TITLE
Crear un archivo "conexion.php" que haga la conexión con la base de datos

### ISSUE THREAD

**Issue by AnderRasoVazquez** [AnderRasoVazquez/proyecto_seguridad#11]
**La idea es incluir este archivo cuando queramos conectarnos a la base de datos**. De no hacerlo así, tendríamos que escribir la conexión en cada archivo y si tuviéramos que cambiar el nombre o la contraseña habría que hacerlo en cada conexión de cada archivo.

La conexion se crea como hice [**en esta línea**](https://github.com/AnderRasoVazquez/proyecto_seguridad/blob/fa230e70fa4b1f83594d95dcfeb5b57ea80048b9/instalacion.php#L7) pero ahora que ya tenemos la base de datos creada, hay que añadir como 4 parámetro el nombre de la base de datos.

Igual es buena idea ponerlo dentro de una función. Así haríamos algo como esto cuando necesitamos conectarnos en otros archivos:

```php
include("conexion.php");
$conn = get_conexion_with_db(); // funcion definida en conexion.php
```

**Comment by SoldierCorp** [comment]
Hola,

¿Lo necesitas con mysqli o prefieres PDO?

**Comment by AnderRasoVazquez** [comment]
Lo estamos haciendo con mysqli.
